urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .helpers import tasks

app_name = 'screener'
urlpatterns = [
    path('', views.index, name="index"),
    path('company/', views.company, name='company'),
    path('update/', views.update, name="update"),
    
    path('update_db/', tasks.update_stock_data, name="update_db"),  #URL per l'aggiornamento automatico
]

models.py
from django.db import models
from django.conf import settings
import os

from django.core.files.storage import FileSystemStorage
import yfinance as yf
import pandas as pd
import numpy as np


ARCHIVE_PATH = str(settings.BASE_DIR) + "/archive/"
path_balancesheet = FileSystemStorage('/balancesheet')
path_income_statement = FileSystemStorage('/income_statement')
path_cash_flow = FileSystemStorage('/cash_flow')
path_history = FileSystemStorage('/history')

# Create your models here.
class Company(models.Model):

    ticker = models.CharField(max_length=10)
    name = models.CharField(max_length=50)
    
    sector = models.CharField(max_length=100, blank=True, null=True)
    industry = models.CharField(max_length=100, blank=True, null=True)
    
    phone = models.CharField(max_length=100, blank=True, null=True)
    website = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    state = models.CharField(max_length=100, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    address = models.CharField(max_length=100, blank=True, null=True)
    
    summary = models.TextField(blank=True, null=True)
    employees = models.IntegerField(blank=True, null=True)

    balancesheet = models.FileField(upload_to = path_balancesheet, blank=True, null=True)
    income_statement = models.FileField(upload_to = path_income_statement, blank=True, null=True)
    cash_flow = models.FileField(upload_to = path_cash_flow, blank=True, null=True)
    history = models.FileField(upload_to=path_history, blank=True, null=True)

    latest_update = models.DateTimeField(auto_now=True)


    class Meta:
        verbose_name_plural="Companies"
        

    def current_price(self):
        try:
            company = yf.Ticker(self.ticker)
            current_price = company.history(period="1d")["Close"].iloc[0]
            return current_price
        except Exception as e:
            # In caso di errori nel recupero del prezzo, restituisci None o un valore di default
            print(f"Error fetching current price for {self.name}: {e}")
            return None
        

    def delete(self):
        # delete the files after checking if they exist
        if os.path.exists(ARCHIVE_PATH + "balancesheet/" + self.ticker + ".csv"):
            os.remove(ARCHIVE_PATH + "balancesheet/" + self.ticker + ".csv")
        if os.path.exists(ARCHIVE_PATH + "cashflow/" + self.ticker + ".csv"):
            os.remove(ARCHIVE_PATH + "cashflow/" + self.ticker + ".csv")
        if os.path.exists(ARCHIVE_PATH + "history/" + self.ticker + ".csv"):
            os.remove(ARCHIVE_PATH + "history/" + self.ticker + ".csv")
        if os.path.exists(ARCHIVE_PATH + "income_statement/" + self.ticker + ".csv"):
            os.remove(ARCHIVE_PATH + "income_statement/" + self.ticker + ".csv")

        super(Company, self).delete()


    def historical_returns(self):
        try:
            history_path = os.path.join(ARCHIVE_PATH, "history", f"{self.ticker}.csv")
            df = pd.read_csv(history_path)
            
            if "Close" in df:
                prices = df["close"].tolist()
                returns = []

                for i in range(1, len(prices)):
                    daily_return = (prices[i] - prices[i - 1]) / prices[i - 1]
                    returns.append(daily_return)

                return returns
        except Exception as e:
            print(f"Error calculating historical returns for {self.name}: {e}")
        
        return []


    def calculate_standard_deviation(self):
        returns = self.historical_returns()
        if returns:
            return np.std(returns)
        return None


    def __str__(self):
        return self.name

forms.py
from django import forms

views.py
from django.shortcuts import render, redirect, HttpResponseRedirect, get_object_or_404
import plotly.io as pi
import datetime as dt
from screener.models import *
from .helpers.db_manager import *
from .helpers.plotter import *
from .helpers.index_calculator import *
from django.contrib import messages
from transactions.models import Portfolio

# Create your views here.
def index(request):
    ## add news 

    portfolios = Portfolio.objects.all()

    context={
        'portfolios':portfolios
    }
    return render(request, 'screener/overview.html', context)


def company(request):
    '''
    Gives an overview of a single company,
    if not in the db it download it
    '''

    try:
        ticker = request.GET['search_query'].upper()

        company = Company.objects.filter(ticker = ticker)

        if not company:
            #create company objects
            create_object(ticker)
            

    ## HANDLE ERRORS
    except Exception as e:
        context = { 
            'req': request.GET['search_query'],
            'error': f"{type(e).__name__} at line {e.__traceback__.tb_lineno} of {__file__}: {e}",
        }
        return render(request, 'screener/404.html', context)

        
    # query db and create context
    company = Company.objects.filter(ticker = ticker)[0]

    # CALCULATE INDICES
    # get income_statement and balancesheet
    income_statement = pd.read_csv(ARCHIVE_PATH + "income_statement/" + str(company.income_statement), index_col=0)
    balancesheet = pd.read_csv(ARCHIVE_PATH + "balancesheet/" + str(company.balancesheet), index_col=0)
    cash_flow = pd.read_csv(ARCHIVE_PATH + "cash_flow/" + str(company.cash_flow), index_col=0)
    
    indices = calculate_indices(financials = income_statement, balancesheet = balancesheet)
    mean_indices = industry_mean(company.industry)

    # CREATE PLOTS
    # get history
    end_date = dt.datetime.today().date()
    history = pd.read_csv(ARCHIVE_PATH + "history/" + str(company.history), index_col='date')
    #convert dates to str
    start_date = dt.datetime.strftime(end_date-pd.DateOffset(years= 10), '%Y-%m-%d')
    end_date = dt.datetime.strftime(end_date, '%Y-%m-%d')

    candle_plot = pi.to_html(    
        plot_candlestick(history.loc[start_date: end_date]), 
        full_html=False, 
        default_height="800px"
        )

    asset_liabilities = pi.to_html(
        plot_balancesheet(balancesheet), 
        full_html=False, 
        )

    revenue_income = pi.to_html(
        plot_income_statement(income_statement), 
        full_html=False, 
        )

    context={

        'ticker':company.ticker,
        'name':company.name,
        'sector':company.sector,
        'industry':company.industry,
        'phone':company.phone,
        'website':company.website,
        'country':company.country,
        'state':company.state,
        'city':company.city,
        'address':company.address,
        'summary':company.summary,
        'employees':company.employees,

        'latest_update':company.latest_update,

        'balancesheet':balancesheet.iloc[:,:1].to_html(classes="table col-12 table-sm table-hover", header=False),
        'income_statement':income_statement.iloc[:,:1].to_html(classes="table col-12 table-sm table-hover", header=False),
        'cash_flow':cash_flow.iloc[:,:1].to_html(classes="table table-sm table-hover", header=False),

        'history':history,
        

        'indices':indices,
        'mean_indices':mean_indices,

        #plots 
        'candlestick': candle_plot,
        'asset_liabilities': asset_liabilities,
        'revenue_income': revenue_income,
        
    }

    return render(request, 'screener/company.html', context)


def update(request):
    
    ticker = request.GET['search_query'].upper()
    update_object(ticker)
    return HttpResponseRedirect('/company/?search_query=' + ticker)

templates/screener/company.html
{% extends "website/base.html" %}
{% load static %}
{% block content %}

{% include "screener/navbar.html" %}
<style>

    /* Stile personalizzato per il colore arancione del bottone */
.btn-custom {
    color: #000; /* Testo nero */
    background-color: #FFD180; /* Colore arancione personalizzato */
    border-color: #FFD180; /* Colore del bordo */
}

</style> 
<div class="m-3 p-3">
    <header class="d-flex flex-row justify-content-around">
        <div class="">
            <h1>{{name}}</h1>
            <h3> ticker: {{ticker}}</h3>
        </div>
        <form action="{% url 'screener:update' %}" method="GET">
            <input class="d-none" type="text" value={{ticker}} aria-label="Search" name="search_query">
            <button type="submit" class="btn btn-custom btn-lg">Update Info</button>
            <p>latest update: {{latest_update}}</p>
        </form>
    </header>

    <div class="d-flex flex-column flex-lg-row m-auto p-3 justify-content-around">
        <div class="col-12 col-lg-4 p-2">
            <button type="button" class="w-100 btn btn-custom m-1" data-bs-toggle="collapse" data-bs-target="#summary">Summary</button>
            <div id="summary" class="collapse show">
                {{summary}}
            </div>
        </div>
        <div class="col-12 col-lg-4 p-2">
            <button type="button" class="w-100 btn btn-custom m-1" data-bs-toggle="collapse" data-bs-target="#generalInfo">General Info</button>
            <div id="generalInfo" class="collapse show">
                <ul class=" list-group mb-3">
                    <li class="list-group-item"><span>sector: </span><span>{{sector}}</span></li>
                    <li class="list-group-item"><span>industry: </span><span>{{industry}}</span></li>
                    <li class="list-group-item"><span>phone: </span><span>{{phone}}</span></li>
                    <li class="list-group-item"><span>website: </span><span><a href="{{website}}">{{website}}</a></span></li>
                    <li class="list-group-item"><span>country: </span><span>{{country}}</span></li>
                    <li class="list-group-item"><span>state: </span><span>{{state}}</span></li>
                    <li class="list-group-item"><span>city: </span><span>{{city}}</span></li>
                    <li class="list-group-item"><span>address: </span><span>{{address}}</span></li>
                    <li class="list-group-item"><span>employees: </span><span>{{employees}}</span></li>
                </ul>
            </div>
        </div>
        <div class="col-12 col-lg-4 p-2">
            <button type="button" class="w-100 btn btn-custom m-1" data-bs-toggle="collapse" data-bs-target="#indices">Indices</button>
            <div id="indices" class="collapse show">
                <table class="table table-sm">
                    <thead>
                        <tr>
                            <th colspan="2">Indices </th>
                            <th> Industry Mean </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <th scope="row">Current Ratio (CR) [+, 1.5 - 2.5]: </th>
                            <td>{{indices.CR}}</td>
                            <td>{{mean_indices.CR}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Quick Ratio (QR) [+, 1 - 2]: </th>
                            <td>{{indices.QR}}</td>
                            <td>{{mean_indices.QR}}</td>
                        </tr>
                        <tr>
                            <th scope="row">fixed asset coverage  [+, >0.7]: </th>
                            <td>{{indices.fixed_asset_coverage}}</td>
                            <td>{{mean_indices.fixed_asset_coverage}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Indebtment Ratio (RI) [-, < 3]: </th>
                            <td>{{indices.RI}}</td>
                            <td>{{mean_indices.RI}}</td>
                        </tr>
                        <tr>
                            <th scope="row">interest expense coverage [+]: </th>
                            <td>{{indices.interest_expense_coverage}}</td>
                            <td>{{mean_indices.interest_expense_coverage}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Return On Debt (ROD) [-]: </th>
                            <td>{{indices.ROD}}</td>
                            <td>{{mean_indices.ROD}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Return On Equity (ROE) [+]: </th>
                            <td>{{indices.ROE}}</td>
                            <td>{{mean_indices.ROE}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Return On Asset (ROA) [+]: </th>
                            <td>{{indices.ROA}}</td>
                            <td>{{mean_indices.ROA}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Return On Sales (ROS) [+]: </th>
                            <td>{{indices.ROS}}</td>
                            <td>{{mean_indices.ROS}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Return On Investment (ROI) [+]: </th>
                            <td>{{indices.ROI}}</td>
                            <td>{{mean_indices.ROI}}</td>
                        </tr>
                        <tr>
                            <th scope="row">Return On Turnover (ROT) [+]: </th>
                            <td>{{indices.ROT}}</td>
                            <td>{{mean_indices.ROT}}</td>
                        </tr>
                        <tr>
                            <th scope="row">active circulating rotation [+]: </th>
                            <td>{{indices.active_circulating_rotation}}</td>
                            <td>{{mean_indices.active_circulating_rotation}}</td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>

<section class="container m-auto">
        <div class="container w-100 d-flex flex-column flex-lg-row">
            <div class="container ">
                <button type="button" class="w-100 btn btn-custom" data-bs-toggle="collapse" data-bs-target="#balancesheet">Balancesheet</button>
                <div id="balancesheet" class="collapse col-12 col-lg-6">
                    {{ balancesheet | safe }}
                </div>
            </div>
            
            <div class="container ">
                <button type="button" class="w-100 btn btn-custom" data-bs-toggle="collapse" data-bs-target="#IncomeStat">Income Statement</button>
                <div id="IncomeStat" class="collapse col-12 col-lg-6">
                    {{ income_statement | safe }}
                </div>
            </div>
        </div>
</section>

<section class="plots container m-auto mt-4">

        <h1 class="text-center"> Financial Statement </h1>
        <div class="container w-100 d-flex flex-column flex-lg-row">
            <div class="container col-12 col-lg-6">
                <h2 class="text-center"> Asset & Liabilities </h2>
                {{ asset_liabilities | safe }}
            </div>
            
            <div class="container col-12 col-lg-6">
                <h2 class="text-center"> Revenue & Income </h2>
                {{ revenue_income | safe }}
            </div>
        </div>

        <h1> Candle Plot </h1>
        <div class="container w-100">
            {{ candlestick | safe }}
        </div>
</section>



{% endblock %}

templates/screener/navbar.html
{% load static %}

{% block navbar %}
<style>

    /* Stile personalizzato per il colore arancione del bottone */
    .btn-custom {
        color: #000; /* Testo nero */
        background-color: #FFD180; /* Colore arancione personalizzato */
        border-color: #FFD180; /* Colore del bordo */
    }
    
  </style> 
<nav class="navbar navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand">NOT FINANCIAL ADVICE</a>
        <ul class="navbar-nav flex-row">
            <li class="nav-item px-3">
                <a class="nav-link" href="{% url 'screener:index' %}">Home</a>
            </li>
            
        </ul>
        <form class="d-flex" action="{% url 'screener:company' %}" method="GET">
            <input class="form-control me-2" type="text" placeholder="Search ticker" aria-label="Search" name="search_query">
            <button class="btn btn-custom" type="submit">Search</button>
        </form>
    </div>
</nav>
<script>
    $('#start_date').val(new Date('2023').toJSON().slice(0,10));    
    $('#end_date').val(new Date().toJSON().slice(0,10));
</script>

{% endblock %} 

templates/screener/overview.html
{% extends "website/base.html" %}
{% load static %}
{% block content %}
{% include "screener/navbar.html" %}
<style>

    /* Stile personalizzato per il colore arancione del bottone */
    .btn-custom {
        color: #000; /* Testo nero */
        background-color: #FFD180; /* Colore arancione personalizzato */
        border-color: #FFD180; /* Colore del bordo */
    }
    
  </style> 
    <div class="container my-5 d-flex flex-column justify-content-around align-items-center">
        <div class="d-flex flex-column flex-md-row justify-content-around flex-wrap">
        {% for portfolio in portfolios %}

            <div class="card my-1" style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ portfolio.name }}</h5>
                    <p class="card-text">{{ portfolio.total_value }}</p>
                    <a class="btn btn-custom" href="{% url 'transactions:portfolio_details' portfolio.pk %}">Details</a>
                </div>  
            </div>
        {% endfor %}
        </div>
    </div>


{% endblock %}